### ISSUE TITLE
Move around in the graph

### ISSUE THREAD

**Issue by jeanbellynck** [jeanbellynck/Cayley-Graph-Generator#25]
Personally I am not the biggest fan but it has been requested, that you could walk around in the space. Since we're using Unity this shouldn't be too hard.

**Comment by p4jo** [comment]
I agree though, that actually the group should look the same way around any vertex, so we might just leave the center and just change the tooltips. This would however ignore this issue as our eventual depiction of the group is not totally symmetric!

We could also start generation of new vertices again after the user centers a new vertex, so that the new center vertex is not close to the ends (leaves) of the graph

**Comment by jeanbellynck** [comment]
Moving around by clicking on a vertex is a fantastic idea.
